services:
  api:
    build: ./server
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENV=dev
      - DEBUG=true
    volumes:
      - ./server:/app/server:ro
  
  web:
    build: ./web
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://api:8000/v1
      - NEXT_PUBLIC_SITE_URL=http://localhost:3000
    depends_on:
      - api
