services:
  api:
    build: ./server
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENV=dev
      - DEBUG=true
    volumes:
      - ./server:/app/server:ro
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
