apiVersion: v1
kind: Namespace
metadata:
  name: aiagentmarket
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: aiagentmarket
spec:
  replicas: 2
  selector:
    matchLabels: { app: api }
  template:
    metadata: { labels: { app: api } }
    spec:
      containers:
        - name: api
          image: your-registry/ai-agent-market-api:1.0.0
          ports: [ { containerPort: 8000 } ]
          env:
            - { name: ENV, value: "prod" }
            - { name: LOG_LEVEL, value: "INFO" }
            - { name: REQUEST_ID_HEADER, value: "X-Request-Id" }
            - { name: REDIS_URL, valueFrom: { secretKeyRef: { name: api-secrets, key: redis_url } } }
          readinessProbe:
            httpGet: { path: /readyz, port: 8000 }
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: 8000 }
            periodSeconds: 10
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits: { cpu: "500m", memory: "512Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: aiagentmarket
spec:
  selector: { app: api }
  ports:
    - name: http
      port: 80
      targetPort: 8000
